### PR TITLE
Capitalization; Markdown syntax

### PR DESCRIPTION
**Pull request by vermiculus**
Two simple commits to fix capitalization and syntax.

Content-oriented pull requests incoming.

### CODE REVIEW

**Comment by luong-komorebi** [comment]
Thank you so much. Sorry for not replying soon. I was busy solving merge conflicts.

**Comment by vermiculus** [comment]
Ah yes, I was too 😄 Looks like you beat me to it.

**Comment by vermiculus** [comment]
You borked it pretty bad… the changes from #2 are gone.

My merge is still good, but it may take some git-fu to use it.

**Comment by luong-komorebi** [comment]
@vermiculus  That was actually a mistake of mine. #2  was the first pull request, whose conflicts I solved but hell, I "accidentally" created a local new branch that was nothing but the same to #2 then push it up . I should have merged not created a new one. I was out of my mind. Just redo everything so that #2  can keep his credits for contributing.... My bad

**Comment by luong-komorebi** [comment]
It is here 407f87d72bcc44acc9085a93318e107cf604ae16 . Probably the worst commit on github of mine.

**Comment by vermiculus** [comment]
Oh, there will be worse. Believe me 😉

**Comment by luong-komorebi** [comment]
Hahaah you're funny. Yeah there will worse hahhaa

**Pull request merged**
